### ISSUE TITLE
Shipping method/calculator setup

### ISSUE THREAD

**Issue by zavan** [MatthewKennedy/spree_shipstation#5]
Hey, thanks for your work on this extension, I have it setup and orders are showing on ShipStation!

The only thing I wasn't able to grasp is how the shipping method/calculator should be setup on Spree. Is this out of scope of the extension?

**Comment by MatthewKennedy** [comment]
Hi @zavan,

The shipping methods and ShipStation are not integrated directly.

You can set your methods up in Spree however you want them, and in ShipStation set up the automation filter to look for the shipping method name and other parameters of the order such as shipping country and map those to your shipping methods in ShipStation.

An example ShipStation automation I use is as follows:

Any order that comes into ShipStation with the shipping method name containing 'Royal Mail' and has a shipping destination of 'U.S', Gets automatically set to 'Royal Mail international Tracked'.

**Comment by zavan** [comment]
Understood! Thanks @MatthewKennedy.
